"""Rational-method surface runoff estimation for a road corridor.

Q = C · i · A  →  (m³/hr) = i(mm/hr)/1000 · A(m²) · IMPERVIOUSNESS

The connected stormwater drain capacity is derived from the road's inlet
count and the rated outflow of its drainage node in the directed graph.
"""

from core.graph_builder import node_outflow_capacity_m3h
from utils.constants import (
    CARRIAGE_WIDTH_M,
    IMPERVIOUSNESS,
    INLET_SPACING_M,
    NETWORK_EFFICIENCY,
)


def catchment_area_m2(road: dict) -> float:
    """Effective contributing area: carriageway length × class width."""
    return road["roadLengthM"] * CARRIAGE_WIDTH_M[road["roadType"]]


def surface_runoff_m3h(road: dict, intensity_mm_hr: float) -> float:
    """Rational method runoff load generated by the road's catchment."""
    return (intensity_mm_hr / 1000.0) * catchment_area_m2(road) * IMPERVIOUSNESS


def inlet_count(road: dict) -> int:
    """Stormwater inlets along the corridor (GCC norm ≈ one per 140 m)."""
    return max(1, round(road["roadLengthM"] / INLET_SPACING_M))


def drain_capacity_m3h(road: dict) -> float:
    """Rated capacity of the drains serving this road's connected node."""
    return (
        node_outflow_capacity_m3h(road["connectedDrainNodeId"])
        * inlet_count(road)
        * NETWORK_EFFICIENCY
    )
